# Generated by Django 5.2.12 on 2026-04-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.IntegerField()),
                ('clients', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('certifications', models.IntegerField()),
            ],
        ),
    ]
