# Generated by Django 5.2.12 on 2026-04-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_projectstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='projects/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='projects/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='projectstats',
            options={'verbose_name_plural': 'Project Stats'},
        ),
    ]
