# Generated by Django 5.2.12 on 2026-04-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_project_alter_projectstats_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='FontAwesome class (e.g. fas fa-graduation-cap)', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
