# Generated by Django 5.2.12 on 2026-07-02 14:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_article_image_alter_experience_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
